# Generated by Django 4.0.4 on 2023-05-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exams',
            fields=[
                ('exam_id', models.BigAutoField(db_column='exam_id', primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('subject_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
        ),
    ]
