# Generated by Django 4.0.4 on 2023-05-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='response_text',
        ),
    ]
