# Generated by Django 4.0.4 on 2023-05-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_score_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='exam_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.exams'),
        ),
    ]
